import { StyleSheet } from 'react-native';
import { fontFamily } from '../typography';
import colors, { type AppColors } from '../../lib/theme/colors';

export const getProfileStyles = (t: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: t.neutral.lighter,
    paddingHorizontal: 20,
  },
  
  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 20,
    paddingTop: 40,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 28,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: t.neutral.lightest,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  
  // Profile Section
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    marginBottom: 24,
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  profileImage: {
    width: 80,
    height: 80,
    marginRight: 16,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: t.brand.primary + '22',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 2,
    borderColor: t.brand.primary + '44',
  },
  profileInfo: {
    flex: 1,
  },
  userName: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 20,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  userEmail: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 8,
  },
  storeTag: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 12,
    color: t.brand.primary,
    backgroundColor: t.brand.primary + '22',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  
  // Plan Card
  planCard: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  planIconImage: {
    width: 32,
    height: 32,
  },
  planInfo: {
    flex: 1,
  },
  planLabel: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 4,
  },
  planName: {
    fontFamily: 'Satoshi-Bold',
    fontSize: 18,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  planDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: colors.neutral.medium,
  },
  planArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // Stats Container
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconRestock: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconEmail: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconImage: {
    width: 32,
    height: 32,
  },
  statTitle: {
    fontFamily: 'Satoshi-Medium',
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 8,
    textAlign: 'center',
  },
  statValue: {
    fontFamily: 'Satoshi-Black',
    fontSize: 32,
    fontWeight: '700',
    color: t.brand.primary,
    marginBottom: 4,
    textAlign: 'center',
  },
  statDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 12,
    color: t.neutral.medium,
    textAlign: 'center',
  },
  
  // Settings Section
  settingsSection: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: t.neutral.lighter,
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  settingInfo: {
    flex: 1,
  },
  settingTitle: {
    fontFamily: 'Satoshi-Medium',
    fontSize: 16,
    fontWeight: '500',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  settingDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: t.neutral.medium,
  },
  
  // Sign Out Section
  signOutSection: {
    paddingBottom: 40,
  },
});