import { StyleSheet } from 'react-native';
import { fontFamily } from '../typography';
import colors, { type AppColors } from '../../lib/theme/colors';

export const getSettingsStyles = (t: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: t.neutral.lightest,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  headerContainer: {
    paddingTop: 50,
    paddingBottom: 20,
  },
  formContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
    overflow: 'hidden',
  },
  actionsContainer: {
    paddingTop: 20,
    paddingBottom: 40,
  },
  
  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
   
    paddingTop: 40,
  },
  headerContent: {
    flex: 1,

  },
  headerTitle: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 28,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: t.neutral.lightest,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  
  // Profile Section
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
    marginBottom: 24,
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  profileImage: {
    width: 80,
    height: 80,
    marginRight: 16,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: t.brand.primary + '22',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 2,
    borderColor: t.brand.primary + '44',
  },
  profileInfo: {
    flex: 1,
  },
  userName: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 20,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  userEmail: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 8,
  },
  storeTag: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 12,
    color: t.brand.primary,
    backgroundColor: t.brand.primary + '22',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  
  // Plan Card
  planCard: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  planHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  planIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  planIconImage: {
    width: 32,
    height: 32,
  },
  planInfo: {
    flex: 1,
  },
  planLabel: {
    fontFamily: fontFamily.satoshi,
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 4,
  },
  planName: {
    fontFamily: 'Satoshi-Bold',
    fontSize: 18,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  planDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: colors.neutral.medium,
  },
  planArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // Stats Container
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  statIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconRestock: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconEmail: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIconImage: {
    width: 32,
    height: 32,
  },
  statTitle: {
    fontFamily: 'Satoshi-Medium',
    fontSize: 14,
    color: t.neutral.medium,
    marginBottom: 8,
    textAlign: 'center',
  },
  statValue: {
    fontFamily: 'Satoshi-Black',
    fontSize: 32,
    fontWeight: '700',
    color: t.brand.primary,
    marginBottom: 4,
    textAlign: 'center',
  },
  statDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 12,
    color: t.neutral.medium,
    textAlign: 'center',
  },
  
  // Settings Section
  settingsSection: {
    backgroundColor: t.neutral.lightest,
    borderRadius: 16,
    marginBottom: 24,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: t.neutral.light,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'hidden',
  },
  settingItem: {
    padding: 0,
    borderBottomWidth: 1,
    borderBottomColor: t.neutral.lighter,
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: t.neutral.lighter,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  settingInfo: {
    flex: 1,
  },
  settingTitle: {
    fontFamily: 'Satoshi-Medium',
    fontSize: 16,
    fontWeight: '500',
    color: t.neutral.darkest,
    marginBottom: 4,
  },
  settingDescription: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: t.neutral.medium,
  },
  
  // Form Field Styles (for editing)
  formFieldContainer: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: t.neutral.lighter,
  },
  formFieldContainerEditing: {
    backgroundColor: t.brand.primary + '0A', // 4% opacity
    borderLeftWidth: 3,
    borderLeftColor: t.brand.primary,
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  formFieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  formFieldLabel: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 16,
    fontWeight: '600',
    color: t.neutral.darkest,
    marginRight: 8,
  },
  editingBadge: {
    backgroundColor: t.brand.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 8,
  },
  editingBadgeText: {
    fontFamily: fontFamily.satoshiBold,
    fontSize: 10,
    color: t.neutral.lightest,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  formFieldInput: {
    fontFamily: fontFamily.satoshi,
    fontSize: 16,
    color: t.neutral.darkest,
    backgroundColor: t.neutral.lightest,
    borderWidth: 1,
    borderColor: t.neutral.light,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    minHeight: 48,
  },
  formFieldInputEditing: {
    borderColor: t.brand.primary,
    borderWidth: 2,
    backgroundColor: t.neutral.lightest,
    shadowColor: t.brand.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  formFieldInputFocused: {
    borderColor: t.brand.primary,
    borderWidth: 2,
  },
  modifiedIndicator: {
    marginLeft: 6,
  },
  
  // Unsaved Changes Banner
  unsavedChangesBanner: {
    backgroundColor: t.status.warning + '15',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: t.status.warning + '40',
    flexDirection: 'row',
    alignItems: 'center',
  },
  unsavedChangesText: {
    fontFamily: fontFamily.satoshiMedium,
    fontSize: 14,
    color: t.status.warning,
    marginLeft: 10,
    flex: 1,
  },
  
  // Sign Out Section
  signOutSection: {
    paddingBottom: 40,
  },
  
  // Action Buttons
  saveButton: {
    marginTop: 25,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: t.brand.primary,
    alignItems: 'center',
    marginHorizontal: 20,
  },
  saveButtonText: {
    color: t.neutral.lightest,
    fontWeight: '600',
    fontSize: 15,
    fontFamily: fontFamily.satoshiMedium,
  },
  resetButton: {
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: t.neutral.lightest,
    borderWidth: 1,
    borderColor: t.neutral.light,
    alignItems: 'center',
    marginHorizontal: 20,
  },
  resetButtonText: {
    color: '#B20000',
    fontWeight: '600',
    fontSize: 15,
    fontFamily: fontFamily.satoshiMedium,
  },
});