import { StyleSheet } from 'react-native';
import { typography } from '../typography';
import colors from '../../lib/theme/colors';

export const welcomeBackStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.neutral.lightest,
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 40,
    justifyContent: 'center',
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  title: {
    ...typography.appTitle,
    color: colors.neutral.darkest,
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    ...typography.bodyMedium,
    color: colors.neutral.medium,
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  methodContainer: {
    alignItems: 'center',
    marginBottom: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.neutral.lighter,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.neutral.light,
  },
  methodLabel: {
    ...typography.bodySmall,
    color: colors.brand.primary,
    fontWeight: '500',
  },
  googleButton: {
    backgroundColor: colors.brand.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  googleButtonText: {
    ...typography.buttonText,
    color: colors.neutral.lightest,
    fontWeight: '600',
  },
  emailButton: {
    backgroundColor: colors.neutral.lightest,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: colors.brand.primary,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  emailButtonText: {
    ...typography.buttonText,
    color: colors.brand.primary,
    fontWeight: '600',
  },
  emailFormContainer: {
    marginBottom: 24,
  },
  input: {
    backgroundColor: colors.neutral.lighter,
    borderWidth: 1,
    borderColor: colors.neutral.light,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 16,
    fontSize: 16,
    color: colors.neutral.darkest,
  },
  button: {
    backgroundColor: colors.brand.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonDisabled: {
    backgroundColor: colors.state.disabled,
    opacity: 0.6,
  },
  buttonText: {
    ...typography.buttonText,
    color: colors.neutral.lightest,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.neutral.light,
  },
  dividerText: {
    ...typography.bodySmall,
    marginHorizontal: 16,
    color: colors.neutral.medium,
    fontWeight: '500',
  },
  secondaryButton: {
    backgroundColor: colors.neutral.lightest,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: colors.brand.primary,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  secondaryButtonText: {
    ...typography.buttonText,
    color: colors.brand.primary,
    fontWeight: '600',
  },
  linkButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  linkButtonText: {
    ...typography.bodySmall,
    color: colors.brand.primary,
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
}); 